### PR TITLE
Use correct docker image name

### PR DESCRIPTION
**Pull request by Silex**
The commits are self-explanatory, ask if unclear.

### CODE REVIEW

**Comment by bbinet** [comment]
thanks @Silex

**Comment by Silex** [comment]
No worries.

Is there any documentation on how to actually use the app? By looking at https://github.com/bbinet/reverse-ssh-manager/blob/master/docker/ssh_command.sh I see that I can use "check" to create devices etc but it's all guesses.

**Comment by bbinet** [comment]
No, I made this app for my own needs, and did not take the time to write docs.

Actually, remote devices will use the ssh check command to create/update devices and see if a tunnel needs to be created:
```
json=$(ssh ${SSH_ARGS} rsm@${SSH_HOST} check ${UUID} ${MINION_ID})
active="$(echo ${json} | jq .active)"
port="$(echo ${json} | jq .port)"
listen="$(echo ${json} | jq .listen)"
if [ "$active" == "true" ]
then
    if [ "$listen" == "true" ]
    then
        echo "Reverse tunnel for ${MINION_ID}[${UUID}] is already open on port ${port}"
        exit 0
    fi
    echo "Opening reverse tunnel for ${MINION_ID}[${UUID}] on port ${port}"
    ssh ${SSH_ARGS} -f -R ${port}:localhost:22 rsm@${SSH_HOST} sleep
fi
```

**Comment by Silex** [comment]
Okay I see. Thanks!

**Pull request merged**
